name: bot_test

services:
  bot:
    build: .
    container_name: bot_test_cnt
    env_file:
      - /home/marshall/ach_test/.env
    secrets:
      - bot_credentials
    volumes:
      - /home/marshall/ach_test/user_bot.db:/ach_bot/user_bot.db
      - /home/marshall/ach_test/:/ach_bot/token.json
secrets:
  bot_credentials:
    file: /home/marshall/ach_test/credentials.json

  
