name: bot_test

services:
  bot:
    build: .
    container_name: bot_test_cnt
    env_file:
      - /home/marshall/ach_test/.env
    secrets:
      - bot_credentials
      - bot_token
    volumes:
      - /home/marshall/ach_test/user_bot.db:/ach_bot/user_bot.db
secrets:
  bot_token:
    file: /home/marshall/ach_test/token.json
  bot_credentials:
    file: /home/marshall/ach_test/credentials.json

  
